# Generated by Django 3.0.8 on 2020-07-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_watchlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
