# Generated by Django 3.0.8 on 2020-07-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200722_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='closedate',
        ),
    ]
